// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: businesses.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (owner_id, name, slug, segment, address, logo_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, name, slug, segment, address, logo_url, created_at, updated_at
`

type CreateBusinessParams struct {
	OwnerID int64       `json:"owner_id"`
	Name    string      `json:"name"`
	Slug    string      `json:"slug"`
	Segment string      `json:"segment"`
	Address pgtype.Text `json:"address"`
	LogoUrl pgtype.Text `json:"logo_url"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness,
		arg.OwnerID,
		arg.Name,
		arg.Slug,
		arg.Segment,
		arg.Address,
		arg.LogoUrl,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Segment,
		&i.Address,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessByID = `-- name: GetBusinessByID :one
SELECT id, owner_id, name, slug, segment, address, logo_url, created_at, updated_at FROM businesses WHERE id = $1
`

func (q *Queries) GetBusinessByID(ctx context.Context, id int64) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessByID, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Segment,
		&i.Address,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessByOwnerID = `-- name: GetBusinessByOwnerID :one
SELECT id, owner_id, name, slug, segment, address, logo_url, created_at, updated_at FROM businesses WHERE owner_id = $1
`

func (q *Queries) GetBusinessByOwnerID(ctx context.Context, ownerID int64) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessByOwnerID, ownerID)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Segment,
		&i.Address,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessBySlug = `-- name: GetBusinessBySlug :one
SELECT id, owner_id, name, slug, segment, address, logo_url, created_at, updated_at FROM businesses WHERE slug = $1
`

func (q *Queries) GetBusinessBySlug(ctx context.Context, slug string) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessBySlug, slug)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Segment,
		&i.Address,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBusiness = `-- name: UpdateBusiness :one
UPDATE businesses
SET name = $2, segment = $3, address = $4, logo_url = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, name, slug, segment, address, logo_url, created_at, updated_at
`

type UpdateBusinessParams struct {
	ID      int64       `json:"id"`
	Name    string      `json:"name"`
	Segment string      `json:"segment"`
	Address pgtype.Text `json:"address"`
	LogoUrl pgtype.Text `json:"logo_url"`
}

func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, updateBusiness,
		arg.ID,
		arg.Name,
		arg.Segment,
		arg.Address,
		arg.LogoUrl,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Segment,
		&i.Address,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
