// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Business struct {
	ID        int64              `json:"id"`
	OwnerID   int64              `json:"owner_id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Segment   string             `json:"segment"`
	Address   pgtype.Text        `json:"address"`
	LogoUrl   pgtype.Text        `json:"logo_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PasswordReset struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Plan struct {
	ID          int64              `json:"id"`
	BusinessID  int64              `json:"business_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	PriceCents  int64              `json:"price_cents"`
	LimitType   string             `json:"limit_type"`
	LimitCount  int32              `json:"limit_count"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Referral struct {
	ID         int64              `json:"id"`
	ReferrerID int64              `json:"referrer_id"`
	ReferredID int64              `json:"referred_id"`
	BusinessID int64              `json:"business_id"`
	Code       string             `json:"code"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID                int64              `json:"id"`
	PlanID            int64              `json:"plan_id"`
	SubscriberID      int64              `json:"subscriber_id"`
	BusinessID        int64              `json:"business_id"`
	PspSubscriptionID pgtype.Text        `json:"psp_subscription_id"`
	Status            string             `json:"status"`
	PeriodEnd         pgtype.Timestamptz `json:"period_end"`
	GraceDeadline     pgtype.Timestamptz `json:"grace_deadline"`
	ReferredBy        pgtype.Int8        `json:"referred_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DiscountPercent   int32              `json:"discount_percent"`
}

type Usage struct {
	ID             int64              `json:"id"`
	SubscriptionID int64              `json:"subscription_id"`
	ValidatedAt    pgtype.Timestamptz `json:"validated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Phone        pgtype.Text        `json:"phone"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
