// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlansByBusinessID = `-- name: CountPlansByBusinessID :one
SELECT COUNT(*) FROM plans WHERE business_id = $1 AND active = true
`

func (q *Queries) CountPlansByBusinessID(ctx context.Context, businessID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPlansByBusinessID, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (business_id, name, description, price_cents, limit_type, limit_count)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, name, description, price_cents, limit_type, limit_count, active, created_at, updated_at
`

type CreatePlanParams struct {
	BusinessID  int64       `json:"business_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	PriceCents  int64       `json:"price_cents"`
	LimitType   string      `json:"limit_type"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.BusinessID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.LimitType,
		arg.LimitCount,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.LimitType,
		&i.LimitCount,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivatePlan = `-- name: DeactivatePlan :exec
UPDATE plans SET active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivatePlan(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivatePlan, id)
	return err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, business_id, name, description, price_cents, limit_type, limit_count, active, created_at, updated_at FROM plans WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id int64) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.LimitType,
		&i.LimitCount,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlansByBusinessID = `-- name: ListPlansByBusinessID :many
SELECT id, business_id, name, description, price_cents, limit_type, limit_count, active, created_at, updated_at FROM plans WHERE business_id = $1 AND active = true ORDER BY created_at
`

func (q *Queries) ListPlansByBusinessID(ctx context.Context, businessID int64) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansByBusinessID, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.LimitType,
			&i.LimitCount,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans
SET name = $2, description = $3, price_cents = $4, limit_type = $5, limit_count = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, business_id, name, description, price_cents, limit_type, limit_count, active, created_at, updated_at
`

type UpdatePlanParams struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	PriceCents  int64       `json:"price_cents"`
	LimitType   string      `json:"limit_type"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.LimitType,
		arg.LimitCount,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.LimitType,
		&i.LimitCount,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
