// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: referrals.sql

package repository

import (
	"context"
)

const countActiveReferralsByReferrer = `-- name: CountActiveReferralsByReferrer :one
SELECT COUNT(*) FROM referrals WHERE referrer_id = $1 AND business_id = $2 AND active = true
`

type CountActiveReferralsByReferrerParams struct {
	ReferrerID int64 `json:"referrer_id"`
	BusinessID int64 `json:"business_id"`
}

func (q *Queries) CountActiveReferralsByReferrer(ctx context.Context, arg CountActiveReferralsByReferrerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveReferralsByReferrer, arg.ReferrerID, arg.BusinessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReferral = `-- name: CreateReferral :one
INSERT INTO referrals (referrer_id, referred_id, business_id, code)
VALUES ($1, $2, $3, $4)
RETURNING id, referrer_id, referred_id, business_id, code, active, created_at
`

type CreateReferralParams struct {
	ReferrerID int64  `json:"referrer_id"`
	ReferredID int64  `json:"referred_id"`
	BusinessID int64  `json:"business_id"`
	Code       string `json:"code"`
}

func (q *Queries) CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error) {
	row := q.db.QueryRow(ctx, createReferral,
		arg.ReferrerID,
		arg.ReferredID,
		arg.BusinessID,
		arg.Code,
	)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.ReferredID,
		&i.BusinessID,
		&i.Code,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralByCode = `-- name: GetReferralByCode :one
SELECT id, referrer_id, referred_id, business_id, code, active, created_at FROM referrals WHERE code = $1 AND active = true
`

func (q *Queries) GetReferralByCode(ctx context.Context, code string) (Referral, error) {
	row := q.db.QueryRow(ctx, getReferralByCode, code)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.ReferredID,
		&i.BusinessID,
		&i.Code,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralByReferredAndBusiness = `-- name: GetReferralByReferredAndBusiness :one
SELECT id, referrer_id, referred_id, business_id, code, active, created_at FROM referrals
WHERE referred_id = $1 AND business_id = $2 AND referrer_id != referred_id AND active = true
LIMIT 1
`

type GetReferralByReferredAndBusinessParams struct {
	ReferredID int64 `json:"referred_id"`
	BusinessID int64 `json:"business_id"`
}

func (q *Queries) GetReferralByReferredAndBusiness(ctx context.Context, arg GetReferralByReferredAndBusinessParams) (Referral, error) {
	row := q.db.QueryRow(ctx, getReferralByReferredAndBusiness, arg.ReferredID, arg.BusinessID)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.ReferredID,
		&i.BusinessID,
		&i.Code,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralCodeBySubscriberAndBusiness = `-- name: GetReferralCodeBySubscriberAndBusiness :one
SELECT code FROM referrals
WHERE referrer_id = $1 AND business_id = $2
LIMIT 1
`

type GetReferralCodeBySubscriberAndBusinessParams struct {
	ReferrerID int64 `json:"referrer_id"`
	BusinessID int64 `json:"business_id"`
}

func (q *Queries) GetReferralCodeBySubscriberAndBusiness(ctx context.Context, arg GetReferralCodeBySubscriberAndBusinessParams) (string, error) {
	row := q.db.QueryRow(ctx, getReferralCodeBySubscriberAndBusiness, arg.ReferrerID, arg.BusinessID)
	var code string
	err := row.Scan(&code)
	return code, err
}
