// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchSubscribersByBusiness = `-- name: SearchSubscribersByBusiness :many
SELECT u.id, u.name, u.email, u.phone,
       s.id as subscription_id, s.status,
       p.name as plan_name
FROM users u
JOIN subscriptions s ON s.subscriber_id = u.id
JOIN plans p ON p.id = s.plan_id
WHERE s.business_id = $1
  AND s.status IN ('active', 'grace')
  AND (u.name ILIKE '%' || $2 || '%' OR u.phone ILIKE '%' || $2 || '%')
ORDER BY u.name
LIMIT 20
`

type SearchSubscribersByBusinessParams struct {
	BusinessID int64       `json:"business_id"`
	Column2    pgtype.Text `json:"column_2"`
}

type SearchSubscribersByBusinessRow struct {
	ID             int64       `json:"id"`
	Name           string      `json:"name"`
	Email          string      `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	SubscriptionID int64       `json:"subscription_id"`
	Status         string      `json:"status"`
	PlanName       string      `json:"plan_name"`
}

func (q *Queries) SearchSubscribersByBusiness(ctx context.Context, arg SearchSubscribersByBusinessParams) ([]SearchSubscribersByBusinessRow, error) {
	rows, err := q.db.Query(ctx, searchSubscribersByBusiness, arg.BusinessID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSubscribersByBusinessRow{}
	for rows.Next() {
		var i SearchSubscribersByBusinessRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.SubscriptionID,
			&i.Status,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
