// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spending.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMonthlyCost = `-- name: CreateMonthlyCost :one
INSERT INTO monthly_costs (business_id, month, monthly_budget_cents)
VALUES ($1, $2, $3)
RETURNING id, business_id, month, infrastructure_cost_cents, claude_api_tokens, total_cost_cents, monthly_budget_cents, created_at, updated_at
`

type CreateMonthlyCostParams struct {
	BusinessID         int64       `json:"business_id"`
	Month              pgtype.Date `json:"month"`
	MonthlyBudgetCents int64       `json:"monthly_budget_cents"`
}

func (q *Queries) CreateMonthlyCost(ctx context.Context, arg CreateMonthlyCostParams) (MonthlyCost, error) {
	row := q.db.QueryRow(ctx, createMonthlyCost, arg.BusinessID, arg.Month, arg.MonthlyBudgetCents)
	var i MonthlyCost
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Month,
		&i.InfrastructureCostCents,
		&i.ClaudeApiTokens,
		&i.TotalCostCents,
		&i.MonthlyBudgetCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSpendingAlert = `-- name: CreateSpendingAlert :one
INSERT INTO spending_alerts (business_id, monthly_cost_id, alert_level, threshold_percent)
VALUES ($1, $2, $3, $4)
RETURNING id, business_id, monthly_cost_id, alert_level, threshold_percent, sent_at, created_at
`

type CreateSpendingAlertParams struct {
	BusinessID       int64  `json:"business_id"`
	MonthlyCostID    int64  `json:"monthly_cost_id"`
	AlertLevel       string `json:"alert_level"`
	ThresholdPercent int32  `json:"threshold_percent"`
}

func (q *Queries) CreateSpendingAlert(ctx context.Context, arg CreateSpendingAlertParams) (SpendingAlert, error) {
	row := q.db.QueryRow(ctx, createSpendingAlert,
		arg.BusinessID,
		arg.MonthlyCostID,
		arg.AlertLevel,
		arg.ThresholdPercent,
	)
	var i SpendingAlert
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.MonthlyCostID,
		&i.AlertLevel,
		&i.ThresholdPercent,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMonthlyCostByID = `-- name: GetMonthlyCostByID :one
SELECT id, business_id, month, infrastructure_cost_cents, claude_api_tokens, total_cost_cents, monthly_budget_cents, created_at, updated_at
FROM monthly_costs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMonthlyCostByID(ctx context.Context, id int64) (MonthlyCost, error) {
	row := q.db.QueryRow(ctx, getMonthlyCostByID, id)
	var i MonthlyCost
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Month,
		&i.InfrastructureCostCents,
		&i.ClaudeApiTokens,
		&i.TotalCostCents,
		&i.MonthlyBudgetCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrCreateMonthlyCost = `-- name: GetOrCreateMonthlyCost :one
SELECT id, business_id, month, infrastructure_cost_cents, claude_api_tokens, total_cost_cents, monthly_budget_cents, created_at, updated_at
FROM monthly_costs
WHERE business_id = $1 AND month = $2
LIMIT 1
`

type GetOrCreateMonthlyCostParams struct {
	BusinessID int64       `json:"business_id"`
	Month      pgtype.Date `json:"month"`
}

func (q *Queries) GetOrCreateMonthlyCost(ctx context.Context, arg GetOrCreateMonthlyCostParams) (MonthlyCost, error) {
	row := q.db.QueryRow(ctx, getOrCreateMonthlyCost, arg.BusinessID, arg.Month)
	var i MonthlyCost
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Month,
		&i.InfrastructureCostCents,
		&i.ClaudeApiTokens,
		&i.TotalCostCents,
		&i.MonthlyBudgetCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentSpendingAlert = `-- name: GetRecentSpendingAlert :one
SELECT id, business_id, monthly_cost_id, alert_level, threshold_percent, sent_at, created_at
FROM spending_alerts
WHERE business_id = $1 AND monthly_cost_id = $2 AND alert_level = $3
ORDER BY sent_at DESC
LIMIT 1
`

type GetRecentSpendingAlertParams struct {
	BusinessID    int64  `json:"business_id"`
	MonthlyCostID int64  `json:"monthly_cost_id"`
	AlertLevel    string `json:"alert_level"`
}

func (q *Queries) GetRecentSpendingAlert(ctx context.Context, arg GetRecentSpendingAlertParams) (SpendingAlert, error) {
	row := q.db.QueryRow(ctx, getRecentSpendingAlert, arg.BusinessID, arg.MonthlyCostID, arg.AlertLevel)
	var i SpendingAlert
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.MonthlyCostID,
		&i.AlertLevel,
		&i.ThresholdPercent,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAllBusinesses = `-- name: ListAllBusinesses :many
SELECT id, owner_id, name, slug, segment, address, logo_url, created_at, updated_at
FROM businesses
ORDER BY id ASC
`

func (q *Queries) ListAllBusinesses(ctx context.Context) ([]Business, error) {
	rows, err := q.db.Query(ctx, listAllBusinesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.Segment,
			&i.Address,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyCosts = `-- name: ListMonthlyCosts :many
SELECT id, business_id, month, infrastructure_cost_cents, claude_api_tokens, total_cost_cents, monthly_budget_cents, created_at, updated_at
FROM monthly_costs
WHERE business_id = $1
ORDER BY month DESC
LIMIT $2 OFFSET $3
`

type ListMonthlyCostsParams struct {
	BusinessID int64 `json:"business_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListMonthlyCosts(ctx context.Context, arg ListMonthlyCostsParams) ([]MonthlyCost, error) {
	rows, err := q.db.Query(ctx, listMonthlyCosts, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlyCost{}
	for rows.Next() {
		var i MonthlyCost
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Month,
			&i.InfrastructureCostCents,
			&i.ClaudeApiTokens,
			&i.TotalCostCents,
			&i.MonthlyBudgetCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpendingAlerts = `-- name: ListSpendingAlerts :many
SELECT id, business_id, monthly_cost_id, alert_level, threshold_percent, sent_at, created_at
FROM spending_alerts
WHERE business_id = $1
ORDER BY sent_at DESC
LIMIT $2 OFFSET $3
`

type ListSpendingAlertsParams struct {
	BusinessID int64 `json:"business_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListSpendingAlerts(ctx context.Context, arg ListSpendingAlertsParams) ([]SpendingAlert, error) {
	rows, err := q.db.Query(ctx, listSpendingAlerts, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendingAlert{}
	for rows.Next() {
		var i SpendingAlert
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.MonthlyCostID,
			&i.AlertLevel,
			&i.ThresholdPercent,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonthlyCostInfrastructure = `-- name: UpdateMonthlyCostInfrastructure :exec
UPDATE monthly_costs
SET infrastructure_cost_cents = infrastructure_cost_cents + $2,
    total_cost_cents = total_cost_cents + $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateMonthlyCostInfrastructureParams struct {
	ID                      int64 `json:"id"`
	InfrastructureCostCents int64 `json:"infrastructure_cost_cents"`
}

func (q *Queries) UpdateMonthlyCostInfrastructure(ctx context.Context, arg UpdateMonthlyCostInfrastructureParams) error {
	_, err := q.db.Exec(ctx, updateMonthlyCostInfrastructure, arg.ID, arg.InfrastructureCostCents)
	return err
}

const updateMonthlyCostTokens = `-- name: UpdateMonthlyCostTokens :exec
UPDATE monthly_costs
SET claude_api_tokens = claude_api_tokens + $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateMonthlyCostTokensParams struct {
	ID              int64 `json:"id"`
	ClaudeApiTokens int64 `json:"claude_api_tokens"`
}

func (q *Queries) UpdateMonthlyCostTokens(ctx context.Context, arg UpdateMonthlyCostTokensParams) error {
	_, err := q.db.Exec(ctx, updateMonthlyCostTokens, arg.ID, arg.ClaudeApiTokens)
	return err
}
