// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE subscriptions SET status = 'cancelled', updated_at = NOW() WHERE id = $1
`

func (q *Queries) CancelSubscription(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, cancelSubscription, id)
	return err
}

const countActiveSubscriptionsByBusinessID = `-- name: CountActiveSubscriptionsByBusinessID :one
SELECT COUNT(*) FROM subscriptions WHERE business_id = $1 AND status IN ('active', 'grace')
`

func (q *Queries) CountActiveSubscriptionsByBusinessID(ctx context.Context, businessID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubscriptionsByBusinessID, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (plan_id, subscriber_id, business_id, psp_subscription_id, status, period_end, referred_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, plan_id, subscriber_id, business_id, psp_subscription_id, status, period_end, grace_deadline, referred_by, created_at, updated_at, discount_percent
`

type CreateSubscriptionParams struct {
	PlanID            int64              `json:"plan_id"`
	SubscriberID      int64              `json:"subscriber_id"`
	BusinessID        int64              `json:"business_id"`
	PspSubscriptionID pgtype.Text        `json:"psp_subscription_id"`
	Status            string             `json:"status"`
	PeriodEnd         pgtype.Timestamptz `json:"period_end"`
	ReferredBy        pgtype.Int8        `json:"referred_by"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.PlanID,
		arg.SubscriberID,
		arg.BusinessID,
		arg.PspSubscriptionID,
		arg.Status,
		arg.PeriodEnd,
		arg.ReferredBy,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.SubscriberID,
		&i.BusinessID,
		&i.PspSubscriptionID,
		&i.Status,
		&i.PeriodEnd,
		&i.GraceDeadline,
		&i.ReferredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiscountPercent,
	)
	return i, err
}

const createSubscriptionWithDiscount = `-- name: CreateSubscriptionWithDiscount :one
INSERT INTO subscriptions (plan_id, subscriber_id, business_id, psp_subscription_id, status, period_end, referred_by, discount_percent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, plan_id, subscriber_id, business_id, psp_subscription_id, status, period_end, grace_deadline, referred_by, created_at, updated_at, discount_percent
`

type CreateSubscriptionWithDiscountParams struct {
	PlanID            int64              `json:"plan_id"`
	SubscriberID      int64              `json:"subscriber_id"`
	BusinessID        int64              `json:"business_id"`
	PspSubscriptionID pgtype.Text        `json:"psp_subscription_id"`
	Status            string             `json:"status"`
	PeriodEnd         pgtype.Timestamptz `json:"period_end"`
	ReferredBy        pgtype.Int8        `json:"referred_by"`
	DiscountPercent   int32              `json:"discount_percent"`
}

func (q *Queries) CreateSubscriptionWithDiscount(ctx context.Context, arg CreateSubscriptionWithDiscountParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscriptionWithDiscount,
		arg.PlanID,
		arg.SubscriberID,
		arg.BusinessID,
		arg.PspSubscriptionID,
		arg.Status,
		arg.PeriodEnd,
		arg.ReferredBy,
		arg.DiscountPercent,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.SubscriberID,
		&i.BusinessID,
		&i.PspSubscriptionID,
		&i.Status,
		&i.PeriodEnd,
		&i.GraceDeadline,
		&i.ReferredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiscountPercent,
	)
	return i, err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT id, plan_id, subscriber_id, business_id, psp_subscription_id, status, period_end, grace_deadline, referred_by, created_at, updated_at, discount_percent FROM subscriptions
WHERE subscriber_id = $1 AND business_id = $2 AND status IN ('active', 'grace')
LIMIT 1
`

type GetActiveSubscriptionParams struct {
	SubscriberID int64 `json:"subscriber_id"`
	BusinessID   int64 `json:"business_id"`
}

func (q *Queries) GetActiveSubscription(ctx context.Context, arg GetActiveSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscription, arg.SubscriberID, arg.BusinessID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.SubscriberID,
		&i.BusinessID,
		&i.PspSubscriptionID,
		&i.Status,
		&i.PeriodEnd,
		&i.GraceDeadline,
		&i.ReferredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiscountPercent,
	)
	return i, err
}

const getActiveSubscriptionBySubscriber = `-- name: GetActiveSubscriptionBySubscriber :one
SELECT id, plan_id, subscriber_id, business_id, psp_subscription_id, status, period_end, grace_deadline, referred_by, created_at, updated_at, discount_percent FROM subscriptions
WHERE subscriber_id = $1 AND status IN ('active', 'grace')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscriptionBySubscriber(ctx context.Context, subscriberID int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionBySubscriber, subscriberID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.SubscriberID,
		&i.BusinessID,
		&i.PspSubscriptionID,
		&i.Status,
		&i.PeriodEnd,
		&i.GraceDeadline,
		&i.ReferredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiscountPercent,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, plan_id, subscriber_id, business_id, psp_subscription_id, status, period_end, grace_deadline, referred_by, created_at, updated_at, discount_percent FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.SubscriberID,
		&i.BusinessID,
		&i.PspSubscriptionID,
		&i.Status,
		&i.PeriodEnd,
		&i.GraceDeadline,
		&i.ReferredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiscountPercent,
	)
	return i, err
}

const getSubscriptionByPSPID = `-- name: GetSubscriptionByPSPID :one
SELECT id, plan_id, subscriber_id, business_id, psp_subscription_id, status, period_end, grace_deadline, referred_by, created_at, updated_at, discount_percent FROM subscriptions WHERE psp_subscription_id = $1
`

func (q *Queries) GetSubscriptionByPSPID(ctx context.Context, pspSubscriptionID pgtype.Text) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByPSPID, pspSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.SubscriberID,
		&i.BusinessID,
		&i.PspSubscriptionID,
		&i.Status,
		&i.PeriodEnd,
		&i.GraceDeadline,
		&i.ReferredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiscountPercent,
	)
	return i, err
}

const listGraceExpiredSubscriptions = `-- name: ListGraceExpiredSubscriptions :many
SELECT id, plan_id, subscriber_id, business_id, psp_subscription_id, status, period_end, grace_deadline, referred_by, created_at, updated_at, discount_percent FROM subscriptions WHERE status = 'grace' AND grace_deadline < NOW()
`

func (q *Queries) ListGraceExpiredSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listGraceExpiredSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.SubscriberID,
			&i.BusinessID,
			&i.PspSubscriptionID,
			&i.Status,
			&i.PeriodEnd,
			&i.GraceDeadline,
			&i.ReferredBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DiscountPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSubscriptions = `-- name: ListPendingSubscriptions :many
SELECT id, plan_id, subscriber_id, business_id, psp_subscription_id, status, period_end, grace_deadline, referred_by, created_at, updated_at, discount_percent FROM subscriptions WHERE status = 'pending'
`

func (q *Queries) ListPendingSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listPendingSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.SubscriberID,
			&i.BusinessID,
			&i.PspSubscriptionID,
			&i.Status,
			&i.PeriodEnd,
			&i.GraceDeadline,
			&i.ReferredBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DiscountPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByBusinessID = `-- name: ListSubscriptionsByBusinessID :many
SELECT s.id, s.plan_id, s.subscriber_id, s.business_id, s.psp_subscription_id, s.status, s.period_end, s.grace_deadline, s.referred_by, s.created_at, s.updated_at, s.discount_percent, u.name as subscriber_name, u.email as subscriber_email, u.phone as subscriber_phone, p.name as plan_name
FROM subscriptions s
JOIN users u ON u.id = s.subscriber_id
JOIN plans p ON p.id = s.plan_id
WHERE s.business_id = $1
ORDER BY s.created_at DESC
`

type ListSubscriptionsByBusinessIDRow struct {
	ID                int64              `json:"id"`
	PlanID            int64              `json:"plan_id"`
	SubscriberID      int64              `json:"subscriber_id"`
	BusinessID        int64              `json:"business_id"`
	PspSubscriptionID pgtype.Text        `json:"psp_subscription_id"`
	Status            string             `json:"status"`
	PeriodEnd         pgtype.Timestamptz `json:"period_end"`
	GraceDeadline     pgtype.Timestamptz `json:"grace_deadline"`
	ReferredBy        pgtype.Int8        `json:"referred_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DiscountPercent   int32              `json:"discount_percent"`
	SubscriberName    string             `json:"subscriber_name"`
	SubscriberEmail   string             `json:"subscriber_email"`
	SubscriberPhone   pgtype.Text        `json:"subscriber_phone"`
	PlanName          string             `json:"plan_name"`
}

func (q *Queries) ListSubscriptionsByBusinessID(ctx context.Context, businessID int64) ([]ListSubscriptionsByBusinessIDRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByBusinessID, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsByBusinessIDRow{}
	for rows.Next() {
		var i ListSubscriptionsByBusinessIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.SubscriberID,
			&i.BusinessID,
			&i.PspSubscriptionID,
			&i.Status,
			&i.PeriodEnd,
			&i.GraceDeadline,
			&i.ReferredBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DiscountPercent,
			&i.SubscriberName,
			&i.SubscriberEmail,
			&i.SubscriberPhone,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscriptionGrace = `-- name: UpdateSubscriptionGrace :exec
UPDATE subscriptions SET status = 'grace', grace_deadline = $2, updated_at = NOW() WHERE id = $1
`

type UpdateSubscriptionGraceParams struct {
	ID            int64              `json:"id"`
	GraceDeadline pgtype.Timestamptz `json:"grace_deadline"`
}

func (q *Queries) UpdateSubscriptionGrace(ctx context.Context, arg UpdateSubscriptionGraceParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionGrace, arg.ID, arg.GraceDeadline)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateSubscriptionStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus, arg.ID, arg.Status)
	return err
}
