// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usages.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDailyUsage = `-- name: CountDailyUsage :one
SELECT COUNT(*) FROM usages
WHERE subscription_id = $1
AND validated_at >= $2::timestamptz
AND validated_at < $3::timestamptz
`

type CountDailyUsageParams struct {
	SubscriptionID int64              `json:"subscription_id"`
	Column2        pgtype.Timestamptz `json:"column_2"`
	Column3        pgtype.Timestamptz `json:"column_3"`
}

func (q *Queries) CountDailyUsage(ctx context.Context, arg CountDailyUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDailyUsage, arg.SubscriptionID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMonthlyUsage = `-- name: CountMonthlyUsage :one
SELECT COUNT(*) FROM usages
WHERE subscription_id = $1
AND validated_at >= $2::timestamptz
AND validated_at < $3::timestamptz
`

type CountMonthlyUsageParams struct {
	SubscriptionID int64              `json:"subscription_id"`
	Column2        pgtype.Timestamptz `json:"column_2"`
	Column3        pgtype.Timestamptz `json:"column_3"`
}

func (q *Queries) CountMonthlyUsage(ctx context.Context, arg CountMonthlyUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMonthlyUsage, arg.SubscriptionID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUsage = `-- name: CreateUsage :one
INSERT INTO usages (subscription_id, validated_at)
VALUES ($1, NOW())
RETURNING id, subscription_id, validated_at
`

func (q *Queries) CreateUsage(ctx context.Context, subscriptionID int64) (Usage, error) {
	row := q.db.QueryRow(ctx, createUsage, subscriptionID)
	var i Usage
	err := row.Scan(&i.ID, &i.SubscriptionID, &i.ValidatedAt)
	return i, err
}

const listUsagesBySubscription = `-- name: ListUsagesBySubscription :many
SELECT id, subscription_id, validated_at FROM usages
WHERE subscription_id = $1
AND validated_at >= $2::timestamptz
AND validated_at < $3::timestamptz
ORDER BY validated_at DESC
`

type ListUsagesBySubscriptionParams struct {
	SubscriptionID int64              `json:"subscription_id"`
	Column2        pgtype.Timestamptz `json:"column_2"`
	Column3        pgtype.Timestamptz `json:"column_3"`
}

func (q *Queries) ListUsagesBySubscription(ctx context.Context, arg ListUsagesBySubscriptionParams) ([]Usage, error) {
	rows, err := q.db.Query(ctx, listUsagesBySubscription, arg.SubscriptionID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Usage{}
	for rows.Next() {
		var i Usage
		if err := rows.Scan(&i.ID, &i.SubscriptionID, &i.ValidatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
